new initd script.

diff --git a/debian/hsn2-fwk.initd b/debian/hsn2-fwk.initd
--- a/debian/hsn2-fwk.initd
+++ b/debian/hsn2-fwk.initd
@@ -10,12 +10,6 @@
 # Description:            Start/Stop the HSN2 Framework daemon.
 ### END INIT INFO
 
-if [ -z "`which java`" ]; then
-	echo "JAVA need to be installed first!"
-	exit 1
-fi
-
-. /lib/lsb/init-functions
 
 NAME="HSN2 Framework"
 HSN2_COMPONENT="framework"
@@ -26,13 +20,60 @@ PIDFILE="/var/run/hsn2-$HSN2_COMPONENT.pid"
 HSN2_COMPONENT_PARAMS="-configPath /etc/hsn2/$HSN2_COMPONENT.conf"
 HSN2_JVM_PARAMS="-Xmx1500m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=1100"
 
-case "$1" in
+MAINCLASS="pl.nask.hsn2.framework.core.Main"
+
+JSVCBIN=`which jsvc`
+
+. /lib/lsb/init-functions
+
+if [ -z "`which java`" ]; then
+	log_failure_msg "Error" "JAVA need to be installed first."
+	exit 1
+fi
+
+
+if [ -z "$JAVA_HOME" -a -d "/usr/lib/jvm/java-7-openjdk-amd64" ]; then
+	#JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64"
+	log_warning_msg "JAVA_HOME is not set.Using default: $JAVA_HOME"
+fi
+
+
+
+use_jsvc_wrapper () {
+	#log_daemon_msg "using jsvc..."
+	case "$1" in
+		start)
+			log_daemon_msg "Starting" "$NAME"
+			$JSVCBIN -home $JAVA_HOME -wait 30 -pidfile ${PIDFILE} $HSN2_JVM_PARAMS -cp $HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $MAINCLASS $HSN2_COMPONENT_PARAMS
+			
+			log_end_msg $?
+			return $?
+			;;
+		stop)
+			log_daemon_msg "Stopping" "$NAME"
+			$JSVCBIN -home $JAVA_HOME -stop -pidfile ${PIDFILE} $HSN2_JVM_PARAMS -cp $HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $MAINCLASS 
+
+			log_end_msg $?
+			return $?
+			;;
+		status)
+			status_of_proc -p $PIDFILE $JSVCBIN $NAME && return 0 || return $?
+			;;
+	esac
+		
+return 0
+}
+
+
+use_start_stop_daemon() {
+	log_daemon_msg "using start-stop-daemon..."
+	case "$1" in
 	start)
 		log_daemon_msg "Starting" "$NAME"
 		cd "$HSN2_COMPONENT_HOME"
 		# workaround (see redmine #6587, #6324)
 		start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --exec /usr/bin/java -- $HSN2_JVM_PARAMS -jar $HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $HSN2_COMPONENT_PARAMS
-		sleep 1
+		sleep 5
 		PID=`cat $PIDFILE`
 		TEST=`ps ax | grep $PID | grep java | sed -e 's/^ *//' | cut -d' ' -f1`
 		if [ -n "$TEST" ]; then
@@ -42,6 +83,7 @@ case "$1" in
 		else
 			log_end_msg 1
 			echo "" > $PIDFILE
+			return 1
 		fi
 		;;
 
@@ -57,7 +99,17 @@ case "$1" in
 		;;
 
 	status)
-		status_of_proc -p $PIDFILE "$JAVA" "$NAME" && exit 0 || exit $?
+		status_of_proc -p $PIDFILE "$JAVA" "$NAME" && return 0 || return $?
 		;;
-esac
-exit 0
+	esac
+return 0
+
+}
+	
+if [ -z "$JSVCBIN"  -o -z "$JAVA_HOME" ]; then
+	use_start_stop_daemon $@
+else
+	use_jsvc_wrapper $@
+fi
+
+exit $?
